### ISSUE TITLE
Why not use some type of consistent hashing? 

### ISSUE THREAD

**Issue by adamJLev** [jaysonsantos/python-binary-memcached#14]
I see that currently a `get` has to  make up to N network operations to fetch its value (N = number of mc nodes), as opposed to just once like in most memcache drivers.
https://github.com/jaysonsantos/python-binary-memcached/blob/master/bmemcached/client.py#L62

What's the reasoning behind this?
Implementing a simple node hash selection algorithm like python-memcache would greatly improve performance by not making extra connections.
e.g.: https://github.com/linsomniac/python-memcached/blob/master/memcache.py#L346

(I know this would disable the replication that happens currently, but memcached is obviously not to be used as a primary data store – and performance is critical)

Either way, thanks for your work @jaysonsantos !

**Comment by jaysonsantos** [comment]
This is fixed on #151
