### ISSUE TITLE
Add support to TLS

### ISSUE THREAD

**Issue by moisesguimaraes** [jaysonsantos/python-binary-memcached#207]
Since version 1.5.13, Memcached [supports TLS][1].

### Motivation

At [OpenStack][2], we use python-binary-memcached in one of our [oslo.cache][3] Memcache backend drivers. To accommodate some cloud security requirements, we will need to enable TLS in Memcached as data must be encrypted in the wire in some scenarios.

I looked over the documentation and couldn't find anything related to TLS support. If there is a way to achieve that, please let us know.

I would like to help with the implementation of this if needed.

[1]: https://github.com/memcached/memcached/wiki/TLS
[2]: https://www.openstack.org/
[3]: https://opendev.org/openstack/oslo.cache

**Comment by jaysonsantos** [comment]
Hey there, right now there is no TLS support.
I didn't read how TLS support is implemented on the binary protocol but I assume it would be just a matter of wrapping the [inner socket](https://github.com/jaysonsantos/python-binary-memcached/blob/master/bmemcached/protocol.py#L144) with a TLS context?
I would be greatly appreciated if you could submit a PR for this.

**Comment by moisesguimaraes** [comment]
Yeah, I got to that line yesterday. Today I'm on PTO but I plan to do it on Monday.

[OFF TOPIC] and... are you Brazilian? [/OFF TOPIC]

**Comment by jaysonsantos** [comment]
Hey @moisesguimaraes thanks for the help!
Yes, I am brazilian :)

**Comment by moisesguimaraes** [comment]
Cool, I got some changes working locally, now I'm trying to figure out how to get it covered by tests.

Would you like me to create a PR already and then we can iterate over it?

**Comment by jaysonsantos** [comment]
Hey, sorry for the delay.
Yes with the PR we can talk abou what you are doing.

**Comment by moisesguimaraes** [comment]
TLS support added in https://github.com/jaysonsantos/python-binary-memcached/pull/211
