### ISSUE TITLE
Outdated docs

### ISSUE THREAD

**Issue by moisesguimaraes** [jaysonsantos/python-binary-memcached#221]
Aren't the memcached servers already run as py.test fixtures?

https://github.com/jaysonsantos/python-binary-memcached/blob/a2d718f5ed4ed6a665b475633192c8793e458c20/docs/intro.rst#L41-L54

**Comment by jaysonsantos** [comment]
Yes, that is true, probably it was leftover when py.test was introduced.

**Comment by moisesguimaraes** [comment]
fixed in https://github.com/jaysonsantos/python-binary-memcached/pull/224
