### ISSUE TITLE
Document compression feature

### ISSUE THREAD

**Issue by timabbott** [jaysonsantos/python-binary-memcached#233]
First, thanks for creating this library!  We're switching Zulip to use it (https://github.com/zulip/zulip/pull/14925).

One question that came up in that discussion was whether this library supports compressing values (https://github.com/zulip/zulip/pull/14925#pullrequestreview-460395051); it turns out that it does, but I don't see that documented for this project (though I do see it on https://github.com/jaysonsantos/django-bmemcached).  It'd be nice if this project documented the feature in its README, and even `django-bmemcached` doesn't document the valid values of the `compression` option.

**Comment by andersk** [comment]
It’s documented here: https://python-binary-memcached.readthedocs.io/en/latest/bmemcached/

**Comment by timabbott** [comment]
Oh, I see, missed the link from the README.
