### ISSUE TITLE
Issue with Django 2.2 + python-binary-memcached 0.29.0

### ISSUE THREAD

**Issue by cchacholiades** [jaysonsantos/python-binary-memcached#234]
While upgrading my Django project I had an issue, find this related question on stackoverflow: https://stackoverflow.com/questions/63471550/upgrading-django-to-2-2-lts-object-is-not-subscriptable 

In my requirements.txt file: 

`python-binary-memcached==0.29.0` - this version makes my code to break `'dict_keys' object is not subscriptable`

if I specify the master branch of this repo directly: 

`git+git://github.com/jaysonsantos/python-binary-memcached@master` - it works ✓ 

---- 

@jaysonsantos Do we need a new release?

**Comment by jaysonsantos** [comment]
Hey there @cchacholiades I've just released 0.30.0, could you give it a try?

**Comment by cchacholiades** [comment]
Many thanks @jaysonsantos
