### ISSUE TITLE
the 0.31.1 tar.gz in pypi without CHANGELOG.md

### ISSUE THREAD

**Issue by HanGuangyu** [jaysonsantos/python-binary-memcached#248]
https://pypi.org/project/python-binary-memcached/#files

I download tar.gz in pypi.org, but it's no CHANGELOG.md.
https://files.pythonhosted.org/packages/e1/88/9a40a7c99d9085d5f5d998651ae40fdf2622513bfa3dd87ff7ce5e08bb48/python-binary-memcached-0.31.1.tar.gz

I don't know the reason, could I get a help?

**Comment by jaysonsantos** [comment]
Hi there @HanGuangyu, I just ran locally the python setup.py sdist bdist_wheel, and it had the changelog, tbh I do not know why it wasn't there before.
But, if you are worried with tampering, you can run this to check that the code there is the same one as here with the following script:

```bash
pypi_check="$(mktemp -d)"
cd "$pypi_check"
echo "Working on $PWD"
wget https://files.pythonhosted.org/packages/e1/88/9a40a7c99d9085d5f5d998651ae40fdf2622513bfa3dd87ff7ce5e08bb48/python-binary-memcached-0.31.1.tar.gz
tar zxvf *.gz
PYPI_HASHES="$(find python-binary-memcached-0.31.1 -iname '*.py' -exec sha256sum {} \; | sed 's/python-binary-memcached-0.31.1/github_version/g')"
git clone https://github.com/jaysonsantos/python-binary-memcached github_version
echo "$PYPI_HASHES" | sha256sum -c -

rm -rf "$pypi_check"
```

**Comment by naufdotal** [comment]
Hi,
I'm sorry for bump this, i found a solution to solved this error by cloning manual this repo :
`git clone https://github.com/jaysonsantos/python-binary-memcached.git`

and then install with pip local package by using this command : 
`pip install -e python-binary-memcached/`

Done
