### ISSUE TITLE
Sorry to interupt, when will the new version be released?

### ISSUE THREAD

**Issue by kongyi182** [jaysonsantos/python-binary-memcached#256]

**Comment by jaysonsantos** [comment]
@kongyi182 there aren't any new features added since the last version, were you looking for something specific?

**Comment by kongyi182** [comment]
I found that there has been no new version for almost 2 years, so I would like to inquire about the version plan.

**Comment by jaysonsantos** [comment]
Nothing planned, especially that the binary protocol is deprecated on memcached.
This lib implements the basic operations and they don't change that often.
I guess you could try and check pylibmc or others for something more up-to date

**Comment by kongyi182** [comment]
thank you
