### ISSUE TITLE
python 3.4.3 “'bytes' object has no attribute 'encode'”

### ISSUE THREAD

**Issue by Wall-ee** [jaysonsantos/python-binary-memcached#43]
AttributeError(“'bytes' object has no attribute 'encode'”)

balabala='pppp'

when i was trying to  get(balabala.encode())

it reports "AttributeError(“'bytes' object has no attribute 'encode'”)"

**Comment by jaysonsantos** [comment]
Thank you!

**Comment by Wall-ee** [comment]
did you mean that i have helped a lot of users across the world?!?!  hahahhahahah ^_^
